<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>mage/cookies.js"></script>
<?php /** @var $cookie Mage_Core_Model_Cookie */
$cookie = Mage::getSingleton('core/cookie');
$badCookiesMessage = Mage::helper('oro_api')->
    __('Your browser does not allow set cookies for third party websites. Please enable it.');?>
<script type="text/javascript">
//<![CDATA[
    //check if we can set cookies in iframe
    if (window.self != window.top) {
        var cookieName = 'isCookiesEnabled';
        if (!window.Mage.Cookies.get(cookieName)) {
            window.Mage.Cookies.set(
                cookieName,
                0,
                null,
                '<?php echo $cookie->getPath();?>',
                '<?php echo $cookie->getDomain();?>'
            );
        }
        if (!window.Mage.Cookies.get(cookieName)) {
            document.body.innerHTML = '<h1><?php echo $badCookiesMessage; ?></h1>';
        }
    }

    if (window.self == window.top && 1 == window.Mage.Cookies.get("is-oro-request")) {
        // If is not iframe and cookie exists then clear it
        window.Mage.Cookies.set(
            "is-oro-request",
            0,
            null,
            '<?php echo $cookie->getPath();?>',
            '<?php echo $cookie->getDomain();?>'
        );
        location.reload();
    }
//]]>
</script>
