<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>mage/cookies.js"></script>
<?php /** @var $cookie Mage_Core_Model_Cookie */ ?>
<?php $cookie = Mage::getSingleton('core/cookie'); ?>
<script type="text/javascript">
//<![CDATA[
    if (window.self == window.top && 1 == window.Mage.Cookies.get("is-oro-request")) {
        // If is not iframe and cookie exists then clear it
        window.Mage.Cookies.set(
            "is-oro-request",
            0,
            null,
            '<?php echo $cookie->getPath();?>',
            '<?php echo $cookie->getDomain();?>'
        );
        location.reload();
    }
//]]>
</script>
